package com.example.syntagi.patient_watch_application.Model2;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class CurrentMedicines extends Data{
    @SerializedName("NAPROZ D TABLET")
    @Expose
    private NAPROZDTABLET nAPROZDTABLET;
    @SerializedName("IBUPROFEN SYRUP")
    @Expose
    private IBUPROFENSYRUP iBUPROFENSYRUP;
    @SerializedName("ACETAMINOPHEN 325MG + TRAMADOL 37.5MG TABLET")
    @Expose
    private ACETAMINOPHEN325MGTRAMADOL375MGTABLET aCETAMINOPHEN325MGTRAMADOL375MGTABLET;

    public NAPROZDTABLET getNAPROZDTABLET() {
        return nAPROZDTABLET;
    }

    public void setNAPROZDTABLET(NAPROZDTABLET nAPROZDTABLET) {
        this.nAPROZDTABLET = nAPROZDTABLET;
    }

    public IBUPROFENSYRUP getIBUPROFENSYRUP() {
        return iBUPROFENSYRUP;
    }

    public void setIBUPROFENSYRUP(IBUPROFENSYRUP iBUPROFENSYRUP) {
        this.iBUPROFENSYRUP = iBUPROFENSYRUP;
    }

    public ACETAMINOPHEN325MGTRAMADOL375MGTABLET getACETAMINOPHEN325MGTRAMADOL375MGTABLET() {
        return aCETAMINOPHEN325MGTRAMADOL375MGTABLET;
    }

    public void setACETAMINOPHEN325MGTRAMADOL375MGTABLET(ACETAMINOPHEN325MGTRAMADOL375MGTABLET aCETAMINOPHEN325MGTRAMADOL375MGTABLET) {
        this.aCETAMINOPHEN325MGTRAMADOL375MGTABLET = aCETAMINOPHEN325MGTRAMADOL375MGTABLET;
    }


}
